dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    check: false
  application:
    name: provider
    id: dubbo-provider
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  scan:
    base-packages: com.qiquinn.security.test.serviceimpl
server:
  port: 10222

spring:
  datasource:
    #使用这个鬼链接8.0以上的mysql需要配置mysql用户密码的加密方式my.ini
    druid:
      password: root
      db-type: mysql
      username: root
      url: jdbc:mysql://localhost:3306/sercurity?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      # ?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/qiquinn/security/dao/*Dao.xml
  type-aliases-package: com.qiquinn.security.entity